-- MySQL Script generated by MySQL Workbench
-- Thu Mar  2 20:28:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_prod
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_prod
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_prod` DEFAULT CHARACTER SET utf8 ;
USE `db_prod` ;

-- -----------------------------------------------------
-- Table `db_prod`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_prod`.`categoria` (
  `categoria_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `qualificacaoCategoria` VARCHAR(255) NOT NULL,
  `descricaoCategoria` VARCHAR(255) NOT NULL,
  `urlimagemCategoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`categoria_id`),
  UNIQUE INDEX `categoria_id_UNIQUE` (`categoria_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `db_prod`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_prod`.`usuario` (
  `usuario_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeusuario` VARCHAR(45) NOT NULL,
  `sobrenomeUsuario` VARCHAR(45) NOT NULL,
  `emailUsuario` VARCHAR(255) NOT NULL,
  `senhaUsuario` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`usuario_id`),
  UNIQUE INDEX `usuario_id_UNIQUE` (`usuario_id` ASC) VISIBLE,
  UNIQUE INDEX `emailUsuario_UNIQUE` (`emailUsuario` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `db_prod`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_prod`.`cidades` (
  `cidade_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeCidade` VARCHAR(45) NOT NULL,
  `estadoCidade` VARCHAR(45) NOT NULL,
  `paisCidade` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cidade_id`),
  UNIQUE INDEX `categoria_id_UNIQUE` (`cidade_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `db_prod`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_prod`.`produtos` (
  `produto_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(45) NOT NULL,
  `descricaoProduto` VARCHAR(255) NOT NULL,
  `linguagensProduto` VARCHAR(45) NOT NULL,
  `categoria_categoria_id` INT UNSIGNED NOT NULL,
  `categoria_categoria_id1` INT UNSIGNED NOT NULL,
  `cidades_cidade_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`produto_id`, `categoria_categoria_id`, `categoria_categoria_id1`, `cidades_cidade_id`),
  UNIQUE INDEX `categoria_id_UNIQUE` (`produto_id` ASC) VISIBLE,
  INDEX `fk_produtos_categoria1_idx` (`categoria_categoria_id1` ASC) VISIBLE,
  INDEX `fk_produtos_cidades1_idx` (`cidades_cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_categoria1`
    FOREIGN KEY (`categoria_categoria_id1`)
    REFERENCES `db_prod`.`categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_cidades1`
    FOREIGN KEY (`cidades_cidade_id`)
    REFERENCES `db_prod`.`cidades` (`cidade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_prod`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_prod`.`imagens` (
  `imagem_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tituloImagem` VARCHAR(45) NOT NULL,
  `urlImagem` VARCHAR(255) NOT NULL,
  `produtos_produto_id` INT UNSIGNED NOT NULL,
  `produtos_categoria_categoria_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`imagem_id`, `produtos_produto_id`, `produtos_categoria_categoria_id`),
  UNIQUE INDEX `categoria_id_UNIQUE` (`imagem_id` ASC) VISIBLE,
  INDEX `fk_imagens_produtos1_idx` (`produtos_produto_id` ASC, `produtos_categoria_categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_imagens_produtos1`
    FOREIGN KEY (`produtos_produto_id` , `produtos_categoria_categoria_id`)
    REFERENCES `db_prod`.`produtos` (`produto_id` , `categoria_categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_prod`.`caracteristicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_prod`.`caracteristicas` (
  `caracteristica_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeCaracteristica` VARCHAR(45) NOT NULL,
  `iconeCaracteristica` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`caracteristica_id`),
  UNIQUE INDEX `categoria_id_UNIQUE` (`caracteristica_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `db_prod`.`produtos_has_caracteristicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_prod`.`produtos_has_caracteristicas` (
  `produtos_produto_id` INT UNSIGNED NOT NULL,
  `produtos_categoria_categoria_id` INT UNSIGNED NOT NULL,
  `caracteristicas_caracteristica_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`produtos_produto_id`, `produtos_categoria_categoria_id`, `caracteristicas_caracteristica_id`),
  INDEX `fk_produtos_has_caracteristicas_caracteristicas1_idx` (`caracteristicas_caracteristica_id` ASC) VISIBLE,
  INDEX `fk_produtos_has_caracteristicas_produtos1_idx` (`produtos_produto_id` ASC, `produtos_categoria_categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_has_caracteristicas_produtos1`
    FOREIGN KEY (`produtos_produto_id` , `produtos_categoria_categoria_id`)
    REFERENCES `db_prod`.`produtos` (`produto_id` , `categoria_categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_caracteristicas_caracteristicas1`
    FOREIGN KEY (`caracteristicas_caracteristica_id`)
    REFERENCES `db_prod`.`caracteristicas` (`caracteristica_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
